linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - bodyclose
    - dupl
    - errorlint
    - exportloopref
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - prealloc
    - revive
    - stylecheck
    - whitespace
    - interfacer
    - maligned
    # New
    - contextcheck
    # - nilaway
# linters-settings:
#   custom:
#     nilaway:
#       type: "module"
#       description: Static analysis tool to detect potential nil panics in Go code.
#       settings:
#         # Settings must be a "map from string to string" to mimic command line flags: the keys are
#         # flag names and the values are the values to the particular flags.
#         include-pkgs: ""
# NilAway can be referred to as `nilaway` just like any other golangci-lint analyzers in other
# parts of the configuration file.
