[[workspace]]
  name = "flasher-api-go"
  directory = "/Users/agravelot/lab/flasher-lerna/apps/api-go"
  setupCommands = [
    "echo \"Setting up flasher\"",
    "docker compose up -d",
    "kitten @ launch --copy-env --cwd=current --title Test nvim ."
  ]
  teardownCommands = []

[[workspace]]
  name = "toto"
